export interface LineageEdge {
  id?: string;  // Optional: stable identifier (auto-generated by parser if omitted)
  from: string; // source table id
  to: string;   // target table or consumer id
  description?: string; // optional description of the transformation/filter
}

export interface Consumer {
  id: string;
  name: string;
  description?: string;
  appearance?: {
    icon?: string;
    color?: string;
  };
  url?: string;
}

export interface ImportEntry {
  from: string;   // Relative path to the source YAML file
  ids?: string[]; // Optional: specific table IDs to import (all tables if omitted)
}

export interface Schema {
  version?: string; // Optional schema version (e.g. "1.0.0")
  tables: Table[];
  relationships: Relationship[];
  lineage?: LineageEdge[]; // Data lineage edges (top-level, separate from ER relationships)
  domains?: Domain[]; // Optional
  consumers?: Consumer[]; // Optional downstream consumers
  annotations?: Annotation[]; // Optional visual notes
  imports?: ImportEntry[]; // Optional cross-file table imports (resolved server-side)
  layout?: Record<string, {
    x: number;
    y: number;
    width?: number;
    height?: number;
    parentId?: string;
  }>;
}

export interface Annotation {
  id: string;
  targetId?: string; // Optional: ID of the object this annotation is attached to
  targetType?: 'table' | 'domain' | 'relationship' | 'lineage' | 'column';
  text: string;
  type: 'sticky' | 'callout';
  color?: string;
  offset: { x: number; y: number }; // Relative to target or absolute if no target
}

export interface Domain {
  id: string;
  name: string;
  description?: string;
  members: string[]; // List of table/consumer IDs
  color?: string;
}

export interface Measure {
  column: string;       // Output column id in this table
  agg: 'sum' | 'count' | 'count_distinct' | 'avg' | 'min' | 'max';
  source_column?: string; // Source column id (or <table_id>.<column_id> for disambiguation)
}

export interface Implementation {
  materialization?: 'table' | 'view' | 'incremental' | 'ephemeral';
  incremental_strategy?: 'merge' | 'append' | 'delete+insert';
  unique_key?: string[];
  partition_by?: Array<{
    field: string;
    granularity?: 'day' | 'month' | 'year' | 'hour';
  }>;
  cluster_by?: string[];
  grain?: string[];
  measures?: Measure[];
}

export interface Table {
  id: string; // Internal name/key
  name: string; // Display name (Conceptual name)
  isImported?: boolean; // True when resolved from an imports: entry (read-only)
  logical_name?: string; // Formal logical name
  physical_name?: string; // Actual database table name
  appearance?: {
    type?: 'fact' | 'dimension' | 'hub' | 'link' | 'satellite' | 'mart' | 'table';
    sub_type?: string; // Generic sub-classification (e.g. transaction, periodic, etc.)
    scd?: string; // History tracking (e.g. type0, type1, type2, etc.)
    icon?: string;
    color?: string;
  };
  conceptual?: {
    description?: string;
    tags?: string[]; // BEAM* tags (WHO, WHAT, WHEN, etc.)
  };
  physical?: { // Optional Table-level physical info
    name?: string;
    schema?: string;
  };
  implementation?: Implementation; // Optional code-generation hints
  columns?: Column[]; // Optional
  sampleData?: any[][]; // New simplified format: 2D array
}

export interface Column {
  id: string; // Logical ID (unique per table)
  logical?: { // Optional
    name: string;
    type: string;
    description?: string;
    isPrimaryKey?: boolean;
    isForeignKey?: boolean;
    isPartitionKey?: boolean;
    additivity?: 'fully' | 'semi' | 'non'; // For Measures
  };
  physical?: { // Optional
    name?: string;
    type?: string;
    constraints?: string[];
  };
}

export interface Relationship {
  id?: string; // Optional: stable identifier (auto-generated by parser if omitted)
  from: {
    table: string;
    column?: string[]; // Optional; parser normalizes string → string[]
  };
  to: {
    table: string;
    column?: string[]; // Optional; parser normalizes string → string[]
  };
  type?: 'one-to-one' | 'one-to-many' | 'many-to-one' | 'many-to-many';
  description?: string; // Optional description of the relationship
}
